### ISSUE TITLE
output_pin entry missing from dashboard

### ISSUE THREAD

**Issue by HitLuca** [mainsail-crew/mainsail#1527]
### Mainsail Version:

v2.7.1

### Browser:

Firefox

### Device:

Laptop

### Operating System:

macOS

### What happened?

Looks like the entry for a beeper isn't showing up as a toggle on the main Mainsail interface (under the miscellaneous card). It was there before but I'm not sure when this issue started happening.

This is my beeper configuration in `printer.cfg`:

```yaml
[output_pin beeper]
pin: EXP1_1
pwm: True
value: 0
shutdown_value: 0
cycle_time: 0.001
scale: 1000
```

### What did you expect to happen instead?

Have the beeper toggle show up in the mainsail ui under the `Miscellaneous` card

### How to reproduce this bug?

create an `output_pin` entry in printer.cfg and check the dashboard

### Additional information:

Other entries are shown in my `Miscellaneous` card, but none of them are `output_pin` instances

![image](https://github.com/mainsail-crew/mainsail/assets/7645621/003cc23a-9e22-47d1-a4b0-ffd94f77ba8b)
